apiVersion: apps/v1
kind: Deployment
metadata:
  name: itemservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itemservice
  template:
    metadata:
      labels:
        app: itemservice
    spec:
      containers:
      - name: itemservice
        image: dockerramkashyap2050/itemservice:latest
        ports:
        - containerPort: 3002
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SECRET
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: ACCESS_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET_KEY
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REGION
      initContainers:
      - name: set-database-url
        image: busybox
        command: ['sh', '-c', 'echo DATABASE_URL=postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME) > /mnt/config/database-url']
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config
      volumes:
      - name: config-volume
        emptyDir: {}
