apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  JWT_SECRET: UmFtS2FzaHlhcA==  # base64 encoded 'RamKashyap'
  ACCESS_KEY: QUtJQVVVQ01ZMlA2T1JNWFhEWg==  # base64 encoded 'AKIAUUCXYZ'
  SECRET_KEY: a1c0bTBpSzRteUI1NVJmdFhaaVBDSzhwUFpJazJy  # base64 encoded 'kW4MmHK4myB55RfvXZPCCi8nPZIk2r'
  REGION: dXMtZWFzdC0y  # base64 encoded 'us-east-2'
